### ISSUE TITLE
mulVec is not exposed

### ISSUE THREAD

**Issue by jochem-brouwer** [herumi/mcl-wasm#10]
At [EthereumJS-VM](https://github.com/ethereumjs/ethereumjs-vm/pull/785) we are using this library in order to get the BLS12-381 EIP in our library.

This EIP also needs access to multi scalar multiplication, i.e. the `mclBnG1_mulVec` and `mclBnG2_mulVec` functions from mcl. They do not seem to be (directly (?)) exposed. Can this function be exposed?

**Comment by herumi** [comment]
Yes, I can expose those functions. There are many functions to be exported for BLS12-381. But is it better to expose them from bls-eth-wasm?
What features do you need?

**Comment by jochem-brouwer** [comment]
[See EIP 2537](https://eips.ethereum.org/EIPS/eip-2537). 

I thus need:

* G1/G2 addition (this is available)
* G1/G2 multiplication (this is also available)
* G1/G2 multiexponentation (this is not readily available, but I think this can be implemented indirectly by using addition/multiplication)
* G1/G2 pairing (this looks like it is available, yet I did not test this)
* Map Fp to G1/G2 (this looks available, although the G1 implementation might not yield the expected results; see [this mcl issue](https://github.com/herumi/mcl/issues/79))

**Comment by herumi** [comment]
I see. To expose mclBnG1_mulVec is an easy task. I'm studying the spec of the map-to-g1 function.

**Comment by herumi** [comment]
I've exported `mclBnG1_mulVec` and `mclBnG2_mulVec`.
https://github.com/herumi/mcl-wasm/commit/774d276f769efcc123975db376769978bb590853

**Comment by jochem-brouwer** [comment]
Thanks a lot @herumi, this works like a charm! 😄
