### ISSUE TITLE
Beautify mcl_c.js and mcl_c512.js to reduce error size

### ISSUE THREAD

**Issue by jochem-brouwer** [herumi/mcl-wasm#11]
When a function of this package throws, these `mcl_c.js` or `mcl_c512.js` seem to throw aswell. Since these scripts do not seem to be beautified, they throw a gigantic error string. Is it possible to "beautify" (i.e. add newlines) these scripts, so the error size reduces?

**Comment by herumi** [comment]
mcl_c.js is automatically generated by Emscripten. mcl.js returns a small error. What process causes a large error?

**Comment by herumi** [comment]
Though I don't know what you want, I've removed mcl_c.js and mcl_c512.js and added mcl_c384_256.js.
It supports BN254, BN_ZSNARK, BLS12-381 curve.

**Comment by herumi** [comment]
I understood what you mean. I changed the compiler option. Is it okay?

**Comment by jochem-brouwer** [comment]
I'm sorry that I was not more clear. I just checked your upgrade; this is exactly what I meant and solves the problem. Thanks a lot!
