### ISSUE TITLE
Checking if a value is on curve?

### ISSUE THREAD

**Issue by jochem-brouwer** [herumi/mcl-wasm#12]
We are implementing the BLS12-381 precompile curves for Ethereum at EthereumJS-VM. One of the error cases of these precompiles is if the point is not on the curve. 

Is it possible to check this with `mcl`? I can create a new `let p = new mcl.G1()` point and then `p.setStr(pointStr)`. Sometimes, this function throws, but it is unclear to me if this is due to the point not being on the curve or some other problem.

Is it possible to explicitly check if a point is on the curve? (Both for `G1` and `G2` points?)

**Comment by herumi** [comment]
The string format of mcl is written in https://github.com/herumi/mcl/blob/master/api.md#string-conversion .

**Comment by jochem-brouwer** [comment]
Sorry for my ignorance. I do not know a lot of elliptic curves. As I understand, this G1 point /should/ be a coordinate which is on the curve, right? It should thus satisfy the EC equation?

If I try to import a point with the expected string format (i.e. "1 <x coord> <y coord>") together with the right number base, and this point is /not/ on the curve, does the function throw? Am I able to explicitly get at the JS-side that this was due to "point not on curve" and not due to some other (internal (?)) error?

**Comment by herumi** [comment]
The argument of Gi.getStr() must be a valid string.
I've added some functions such as getX(), setX(), isValid(), isValidOrder().
G1 has three arguments of Fp X, Y, Z.
G2 has three arguments of Fp2 X, Y, Z.

[X:Y:Z] is Jacobi coordinate representation of a point of an elliptic curve.

If you want to an Affine point (x, y) to g1 where x and y is an instance of mcl.Fp,

```
const one = new mcl.Fp()
one.setInt(1)
const g1 = new mcl.G1()
g1.setX(x)
g1.setY(y)
g1.setZ(one)
```
and check the correctness by g1.isValid(), which returns whether the point is on the elliptic curve or not.

g1.isValidOrder() returns whether g1 has the correct order r, which means r times g1 = 0.

**Comment by herumi** [comment]
>this was due to "point not on curve" and not due to some other (internal (?)) error?

setStr() throws an exception if there is a wrong string as Fp or the point is not on the elliptic curve.

**Comment by jochem-brouwer** [comment]
Thanks a lot! We use `isValid()` in order to check this.
