### ISSUE TITLE
`ReferenceError: window is not defined` upon import

### ISSUE THREAD

**Issue by benediamond** [herumi/mcl-wasm#23]
In a react application using webpack 5.61.0, the import statement
```javascript
import mcl from "mcl-wasm/browser";
```
triggers:
```javascript
ReferenceError: window is not defined
```
i am happy to provide further diagnostic information, but i am not sure how to attain it because the stack trace is not really decipherable. thanks.

**Comment by benediamond** [comment]
i installed it using `yarn add mcl-wasm`. is this correct?

**Comment by herumi** [comment]
What browser do you use?
Open
https://herumi.github.io/mcl-wasm/browser/demo.html
and run 'test IBE'. Does it run?

**Comment by benediamond** [comment]
but i noticed in that test page, you directly import `mcl.js` as a script in your html page. whereas I'd rather import it from within my other javascript files, not directly in the html file.

**Comment by herumi** [comment]
Thanks for the information.
When I check `import mcl from 'mcl-wasm/';` with React before, it runs well.
I'll check it again for the latest version.

**Comment by herumi** [comment]
https://github.com/herumi/misc/tree/master/react/test2 is a tiny sample of mcl-wasm ith React and webpack. It runs well. Could you check it?
```
import mcl from "mcl-wasm/browser";
```

**Comment by benediamond** [comment]
after going to `public/`, i get:
> this is a test
> 1234567:894452905640319049678920984443007266612159160327439547902176562641551440349

with no errors in the console. so it looks like it works.

i still don't know what is going wrong on my end, but I can investigate further tomorrow. either way, this test will hopefully help me bootstrap a working setup. thanks for this. hopefully tomorrow i can diagnose and let you know what the issue is.

**Comment by benediamond** [comment]
FYI, here is my stack trace:
```javascript
ReferenceError: window is not defined
    at Object../node_modules/mcl-wasm/browser/src/index-browser.js (index-browser.js:3)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Module../src/crypto/worker.js (bn128.js:20)
    at __webpack_require__ (bootstrap:24)
    at bootstrap:49
    at Function.__webpack_require__.O (chunk loaded:23)
    at __webpack_require__.x (bootstrap:50)
```
still working on diagnosing this.

**Comment by benediamond** [comment]
update: i am able to get this to work in my _main_ (non-worker) scripts. when i try to load `mcl` _inside a worker_, i get the error.

**Comment by herumi** [comment]
Could you write the minimum example?

**Comment by benediamond** [comment]
I invited you to a repo containing a minimal example. can you let me know if you received it and can reproduce?

**Comment by herumi** [comment]
Worker has not window but self, so I fixed mcl-wasm to use it.
https://github.com/herumi/mcl-wasm/commit/eda1ff4a40d857be3fdec1a669088851b1f67a6f

cf. https://stackoverflow.com/a/48183681

1. Add `resolve: { fallback: { "crypto": false} } ,` to `webpack.config.js`.
2. Use `import mcl from "mcl-wasm/browser";` instead of `import {mcl} from "mcl-wasm/browser";`.

Then, I think it will run well.

**Comment by benediamond** [comment]
works. many thanks!

**Comment by benediamond** [comment]
hello! it seems that somewhere strictly after `0.9.0` but on-or-before `1.0.3`, this issue reverted. can you please confirm whether you are able to reproduce? if not, i can provide an MWE. thanks.

**Comment by herumi** [comment]
Thank you for the information.

Please use
```javascript
import * as mcl from 'mcl-wasm';
```
instead of
```javascript
import mcl from "mcl-wasm";
```

**Comment by benediamond** [comment]
this appears to work! many thanks as always for the great work.
