### ISSUE TITLE
run `mcl-wasm` inside SES

### ISSUE THREAD

**Issue by firnprotocol** [herumi/mcl-wasm#28]
hello @herumi, thank you for the incredible work. i wanted to cross-post this issue, as I may believe it may be a `mcl-wasm` issue.

https://github.com/MetaMask/metamask-extension/issues/17064

the issue is that when `mcl-wasm` runs inside the [SES](https://www.npmjs.com/package/ses) environment, I get the following error:

```javascript
➤ YN0000: [snap]: SES_UNHANDLED_REJECTION: [TypeError <Object <Object <[Object: null prototype] {}>>>: scriptDirectory.indexOf is not a function
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53750:37)
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53598:29)
➤ YN0000: [snap]:   at Generator.next (<anonymous>)
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53381:73)
➤ YN0000: [snap]:   at new Promise (<anonymous>)
➤ YN0000: [snap]:   at __awaiter (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53360:16)
➤ YN0000: [snap]:   at Object.initializeMcl (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53597:74)
➤ YN0000: [snap]:   at 324.ethers (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:59973:27)
➤ YN0000: [snap]:   at o (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:38:19)
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:40:20)]
```

an MWE is given in [`firnprotocol-snap-mcl-wasm-mwe`](https://github.com/firnprotocol/snap-mcl-wasm-mwe).

to reproduce:
1. clone [my MWE](https://github.com/firnprotocol/snap-mcl-wasm-mwe)
2. run `yarn start`
3. navigate to localhost:8000 in a browser tab with Flask enabled (i needed to install it in a separate chrome profile from the one with regular metamask).
4. click "connect" and "send message".

huge thanks in advance for your attention.

**Comment by firnprotocol** [comment]
update: in https://github.com/firnprotocol/snap-mcl-wasm-mwe/commit/a990e921fd457fa2e56eb4f6aac7d85b81b541f8, i simplified it even further, and triggered the error in the command line during build. it's enough just to do `mcl.init(mcl.BN_SNARK1)`. to trigger the error.

**Comment by herumi** [comment]
Though I don't know SES, does it support WASM?

**Comment by firnprotocol** [comment]
i believe it does: in https://github.com/MetaMask/snaps-monorepo/pull/242, they were able to run WASM inside a snap. i haven't looked into the details yet.

**Comment by firnprotocol** [comment]
this file might be helpful: https://github.com/MetaMask/snaps-monorepo/pull/242/files#diff-1797d042b27560cb70be9763e3036c30d48ac81478df5592636c61a74e2e9098

**Comment by herumi** [comment]
Emscripten generates mcl_c.js, so I can't control it.

> YN0000: [snap]: SES_UNHANDLED_REJECTION: [TypeError <Object <Object <[Object: null prototype] {}>>>: scriptDirectory.indexOf is not a function

This error is probably https://github.com/herumi/mcl-wasm/blob/master/src/mcl_c.js#L114-L122 .

I don't think that [some variables setting](https://github.com/herumi/mcl-wasm/blob/master/src/mcl_c.js#L30-L34) work.
If we correct the values on SES, then it will run well.

**Comment by herumi** [comment]
I'll try the latest Emscripten.

**Comment by herumi** [comment]
>clone my MWE
>run yarn start

I clone https://github.com/firnprotocol/snap-mcl-wasm-mwe and `yarn install && yarn start`, then it shows an error

>yarn install
>00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

What should I do?

**Comment by firnprotocol** [comment]
maybe try [theses instructions](https://yarnpkg.com/getting-started/migration#step-by-step)? try
```bash
npm install -g yarn
yarn set version latest
```

**Comment by firnprotocol** [comment]
can you look at [this](https://stackoverflow.com/a/47680012/8360867)?

**Comment by firnprotocol** [comment]
hi. could i please follow up—have you been able to look at this, by any chance? thanks again in advance.

**Comment by herumi** [comment]
Thank you for the information about yarn. I could run it.
I can't respond so quickly because I have many jobs, and this support is done during my break time (This development is my hobby.)

As I wrote at https://github.com/herumi/mcl-wasm/issues/28#issuecomment-1366426669 , the problem is caused before calling mcl-wasm code. I'll try to run a minimum sample generated Emscripten at SES environments.

**Comment by firnprotocol** [comment]
> As I wrote at https://github.com/herumi/mcl-wasm/issues/28#issuecomment-1366426669 , the problem is caused before calling mcl-wasm code.

right, understood. this seems like a good thing actually—easier to debug / fix?

> I can't respond so quickly because I have many jobs, and this support is done during my break time

sure. please keep me updated if you get a chance to look further. thanks again in advance for your work.

**Comment by herumi** [comment]
I make [a minimum sample](https://github.com/herumi/misc/tree/main/wasm/sample) of wasm using [emscripten](https://emscripten.org/).

[sample_c.js](https://github.com/herumi/misc/blob/main/wasm/sample/src/sample_c.js) is a generated wasm file from [src/sample.cpp](https://github.com/herumi/misc/blob/main/wasm/sample/src/sample.cpp) by `make`.

You can run it.
```
cd sample
% npm test

> sample@1.0.0 test
> tsc && node test/test.js

initializeSample
func(123)=10123
sample.init
```

Next, I make a symbolic link `snap-mcl-wasm-mwe/node_modules/sample` from the sample directory, and modified `packages/snap/src/index.ts` like as
```
packages/snap/src/index.ts
index 1a3ed4a..320669b 100644
--- a/packages/snap/src/index.ts
+++ b/packages/snap/src/index.ts
@@ -1,10 +1,16 @@
 import { OnRpcRequestHandler } from '@metamask/snap-types';
-import * as mcl from 'mcl-wasm';
+//import * as mcl from 'mcl-wasm';
+import * as sample from 'sample';
 import { ethers } from 'ethers';

-mcl.init(mcl.BN_SNARK1).then(() => { // key problem
-  console.log('initialized!');
-});
+//mcl.init(mcl.BN_SNARK1).then(() => { // key problem
+//  console.log('initialized!');
+//});
+
+sample.init().then(() => {
+  console.log('OK')
+})
+console.log('PPP');
```
and run `yarn start`, then it shows an error such as
```
snap-mcl-wasm-mwe% yarn start
? YN0000: [site]: Process started
? YN0000: [snap]: Process started
? YN0000: [snap]: Watching 'src/' for changes...
? YN0000: [snap]: Build success: 'src/index.ts' bundled as 'dist/bundle.js'!
? YN0000: [snap]: initializeSample
? YN0000: [snap]: PPP
? YN0000: [snap]: SES_UNHANDLED_REJECTION: [TypeError <Object <Object <[Object: null prototype] {}>>>: scriptDirectory.indexOf is not a function
? YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/home/shigeo/Program/snap-mcl-wasm-mwe/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:428:37)
? YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/home/shigeo/Program/snap-mcl-wasm-mwe/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:117:27)
? YN0000: [snap]:   at Generator.next (<anonymous>)
? YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/home/shigeo/Program/snap-mcl-wasm-mwe/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:104:73)
? YN0000: [snap]:   at new Promise (<anonymous>)
? YN0000: [snap]:   at __awaiter (eval at <anonymous> (eval at makeEvaluateFactory (/home/shigeo/Program/snap-mcl-wasm-mwe/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:83:16)
...
```

The error seems the same as what you reported.
So, how about reporting this to the developers of SES and emscripten to consider each environment?

**Comment by herumi** [comment]
>right, understood. this seems like a good thing actually—easier to debug / fix?

Maybe it will run well if we can set these variables in sample_c.js or mcl_c.js, but I don't know SES.
```
        // Determine the runtime environment we are in. You can customize this by
        // setting the ENVIRONMENT setting at compile time (see settings.js).
        var ENVIRONMENT_IS_WEB = false;
        var ENVIRONMENT_IS_WORKER = false;
        var ENVIRONMENT_IS_NODE = false;
        var ENVIRONMENT_IS_SHELL = false;
        ENVIRONMENT_IS_WEB = typeof window === 'object';
        ENVIRONMENT_IS_WORKER = typeof importScripts === 'function';
```

**Comment by firnprotocol** [comment]
hi @herumi, thanks for the response.

i am having trouble reproducing your setup, though i am probably doing something silly. after modifying `index.ts` as you did, i symbolic link and run as below:
```bash
$ snap-mcl-wasm-mwe % cd node_modules 
$ node_modules % ln -s ~/misc/wasm/sample ./sample 
$ node_modules % cd ..
$ snap-mcl-wasm-mwe % yarn start
➤ YN0000: [site]: Process started
➤ YN0000: [snap]: Process started
➤ YN0000: [snap]: Watching 'src/' for changes...
➤ YN0000: [snap]: Browserslist: caniuse-lite is outdated. Please run:
➤ YN0000: [snap]:   npx browserslist@latest --update-db
➤ YN0000: [snap]:   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
➤ YN0000: [snap]: Build error: Can't walk dependency graph: Cannot find module 'sample' from '/Users/firnprotocol/snap-mcl-wasm-mwe/packages/snap/src/index.ts'
➤ YN0000: [snap]:     required by /Users/firnprotocol/snap-mcl-wasm-mwe/packages/snap/src/index.ts
➤ YN0000: [snap]: Error: Can't walk dependency graph: Cannot find module 'sample' from '/Users/firnprotocol/snap-mcl-wasm-mwe/packages/snap/src/index.ts'
➤ YN0000: [snap]:     required by /Users/firnprotocol/snap-mcl-wasm-mwe/packages/snap/src/index.ts
➤ YN0000: [snap]:     at /Users/firnprotocol/snap-mcl-wasm-mwe/node_modules/resolve/lib/async.js:146:35
➤ YN0000: [snap]:     at processDirs (/Users/firnprotocol/snap-mcl-wasm-mwe/node_modules/resolve/lib/async.js:299:39)
➤ YN0000: [snap]:     at isdir (/Users/firnprotocol/snap-mcl-wasm-mwe/node_modules/resolve/lib/async.js:306:32)
➤ YN0000: [snap]:     at /Users/firnprotocol/snap-mcl-wasm-mwe/node_modules/resolve/lib/async.js:34:69
➤ YN0000: [snap]:     at FSReqCallback.oncomplete (node:fs:199:21) {
➤ YN0000: [snap]:   code: 'MODULE_NOT_FOUND',
➤ YN0000: [snap]:   stream: Labeled {
➤ YN0000: [snap]:     _readableState: ReadableState {
➤ YN0000: [snap]:       objectMode: true,
➤ YN0000: [snap]:       highWaterMark: 16,
➤ YN0000: [snap]:       buffer: BufferList { length: 0 },
➤ YN0000: [snap]:       length: 0,
➤ YN0000: [snap]:       pipes: [Labeled],
➤ YN0000: [snap]:       pipesCount: 1,
➤ YN0000: [snap]:       flowing: true,
➤ YN0000: [snap]:       ended: false,
➤ YN0000: [snap]:       endEmitted: false,
➤ YN0000: [snap]:       reading: true,
➤ YN0000: [snap]:       sync: false,
➤ YN0000: [snap]:       needReadable: true,
➤ YN0000: [snap]:       emittedReadable: false,
➤ YN0000: [snap]:       readableListening: false,
➤ YN0000: [snap]:       resumeScheduled: false,
➤ YN0000: [snap]:       destroyed: false,
➤ YN0000: [snap]:       defaultEncoding: 'utf8',
➤ YN0000: [snap]:       awaitDrain: 0,
➤ YN0000: [snap]:       readingMore: false,
➤ YN0000: [snap]:       decoder: null,
➤ YN0000: [snap]:       encoding: null
➤ YN0000: [snap]:     },
➤ YN0000: [snap]:     readable: true,
➤ YN0000: [snap]:     _events: [Object: null prototype] {
➤ YN0000: [snap]:       end: [Array],
➤ YN0000: [snap]:       error: [Function (anonymous)],
➤ YN0000: [snap]:       data: [Function: ondata],
➤ YN0000: [snap]:       _mutate: [Function]
➤ YN0000: [snap]:     },
➤ YN0000: [snap]:     _eventsCount: 4,
➤ YN0000: [snap]:     _maxListeners: undefined,
➤ YN0000: [snap]:     _writableState: WritableState {
➤ YN0000: [snap]:       objectMode: true,
➤ YN0000: [snap]:       highWaterMark: 16,
➤ YN0000: [snap]:       finalCalled: false,
➤ YN0000: [snap]:       needDrain: false,
➤ YN0000: [snap]:       ending: true,
➤ YN0000: [snap]:       ended: true,
➤ YN0000: [snap]:       finished: true,
➤ YN0000: [snap]:       destroyed: false,
➤ YN0000: [snap]:       decodeStrings: true,
➤ YN0000: [snap]:       defaultEncoding: 'utf8',
➤ YN0000: [snap]:       length: 0,
➤ YN0000: [snap]:       writing: false,
➤ YN0000: [snap]:       corked: 0,
➤ YN0000: [snap]:       sync: false,
➤ YN0000: [snap]:       bufferProcessing: false,
➤ YN0000: [snap]:       onwrite: [Function (anonymous)],
➤ YN0000: [snap]:       writecb: null,
➤ YN0000: [snap]:       writelen: 0,
➤ YN0000: [snap]:       bufferedRequest: null,
➤ YN0000: [snap]:       lastBufferedRequest: null,
➤ YN0000: [snap]:       pendingcb: 0,
➤ YN0000: [snap]:       prefinished: true,
➤ YN0000: [snap]:       errorEmitted: false,
➤ YN0000: [snap]:       bufferedRequestCount: 0,
➤ YN0000: [snap]:       corkedRequestsFree: [CorkedRequest]
➤ YN0000: [snap]:     },
➤ YN0000: [snap]:     writable: false,
➤ YN0000: [snap]:     allowHalfOpen: true,
➤ YN0000: [snap]:     _options: { objectMode: true },
➤ YN0000: [snap]:     _wrapOptions: { objectMode: true },
➤ YN0000: [snap]:     _streams: [ [Deps] ],
➤ YN0000: [snap]:     length: 1,
➤ YN0000: [snap]:     label: 'deps',
➤ YN0000: [snap]:     [Symbol(kCapture)]: false
➤ YN0000: [snap]:   }
➤ YN0000: [snap]: }
➤ YN0000: [snap]: Write error: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
➤ YN0000: [snap]: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
➤ YN0000: [snap]:     at Object.writeFile (node:internal/fs/promises:881:5)
➤ YN0000: [snap]:     at writeBundleFile (/Users/firnprotocol/snap-mcl-wasm-mwe/node_modules/@metamask/snaps-cli/dist/cmds/build/utils.js:26:29)
➤ YN0000: [snap]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
➤ YN0000: [snap]:     at async Readable.<anonymous> (/Users/firnprotocol/snap-mcl-wasm-mwe/node_modules/@metamask/snaps-cli/dist/cmds/build/bundle.js:63:61) {
➤ YN0000: [snap]:   code: 'ERR_INVALID_ARG_TYPE'
➤ YN0000: [snap]: }
➤ YN0000: [snap]: Write error: Failed to unlink mangled file.
➤ YN0000: [snap]: [Error: ENOENT: no such file or directory, unlink 'dist/bundle.js'] {
➤ YN0000: [snap]:   errno: -2,
➤ YN0000: [snap]:   code: 'ENOENT',
➤ YN0000: [snap]:   syscall: 'unlink',
➤ YN0000: [snap]:   path: 'dist/bundle.js'
➤ YN0000: [snap]: }
```
`misc/wasm/sample` is in a clean state from the clone. (the build results seem there already.) do i need to modify `package.json`? sorry for the naive questions.

**Comment by herumi** [comment]
How about making a symbolic link of sample in `snap-mcl-wasm-mwe/packages/snap/` , and modifying `snap/src`index.ts` like as

```diff
diff --git a/packages/snap/src/index.ts b/packages/snap/src/index.ts
index 1a3ed4a..8b2dc14 100644
--- a/packages/snap/src/index.ts
+++ b/packages/snap/src/index.ts
@@ -1,10 +1,15 @@
 import { OnRpcRequestHandler } from '@metamask/snap-types';
-import * as mcl from 'mcl-wasm';
+//import * as mcl from 'mcl-wasm';
+import * as sample from '../sample/src';
 import { ethers } from 'ethers';

-mcl.init(mcl.BN_SNARK1).then(() => { // key problem
-  console.log('initialized!');
+//mcl.init(mcl.BN_SNARK1).then(() => { // key problem
+//  console.log('initialized!');
+//});
+sample.init().then(() => {
+  console.log('SAMPLE init!');
 });
+console.log('PPP')
```

Could you give me a minimum sample of SES to show hello world (without packages/site and the other packagess)?

**Comment by firnprotocol** [comment]
got it. i was able to reproduce; thanks.
> Could you give me a minimum sample of SES to show hello world (without packages/site and the other packagess)?

i will work on this, and get back you within a few days. thanks again.

**Comment by firnprotocol** [comment]
hi @herumi. i have investigated this a bit.

i was able to "fix" the issue by making some small changes to `sample_c.js`. please see [this commit](https://github.com/firnprotocol/snap-mcl-wasm-mwe/commit/621c595226120ccbc5913d415d7f61664d257e06) for the minimal change I was able to find.

obviously, it is not desirable to modify auto-generated content from emscripten. but this may be the easiest way? either that, or we may need to contact SES and/or Emscripten. maybe you can publish a special "version" of `mcl`, in which this change is made....?

let me try to describe the issue in a bit more detail. in SES, `ENVIRONMENT_IS_WEB` [gets set to true](https://github.com/firnprotocol/snap-mcl-wasm-mwe/blob/621c595226120ccbc5913d415d7f61664d257e06/packages/snap/sample/src/sample_c.js#L119), since `typeof window === 'object'`. but emscripten [assumes](https://github.com/firnprotocol/snap-mcl-wasm-mwe/blob/621c595226120ccbc5913d415d7f61664d257e06/packages/snap/sample/src/sample_c.js#L247-L249) that it will _also_ be true that `typeof document !== 'undefined'`. but this assumption doesn't hold in SES, so `scriptDirectory` is never set, and errors [here](https://github.com/firnprotocol/snap-mcl-wasm-mwe/blob/621c595226120ccbc5913d415d7f61664d257e06/packages/snap/sample/src/sample_c.js#L259). but the variable `scriptDirectory` is only used (indirectly) [here](https://github.com/firnprotocol/snap-mcl-wasm-mwe/blob/621c595226120ccbc5913d415d7f61664d257e06/packages/snap/sample/src/sample_c.js#L1589-L1591), and i was able to comment that out without issue. likewise, `fetch` doesn't work correctly in SES, and causes an error [here](https://github.com/firnprotocol/snap-mcl-wasm-mwe/blob/621c595226120ccbc5913d415d7f61664d257e06/packages/snap/sample/src/sample_c.js#L1621), but i was able to comment out the entire block, and use [the other path](https://github.com/firnprotocol/snap-mcl-wasm-mwe/blob/621c595226120ccbc5913d415d7f61664d257e06/packages/snap/sample/src/sample_c.js#L1631) instead, without issue.

let me know your thoughts? huge thanks for your help.

**Comment by firnprotocol** [comment]
i am wondering if the problematic behavior can be disabled using the right Emscripten build flags.

it seems that what we want is to disable asynchronous fetching of the WASM binary. see [these docs](https://emscripten.org/docs/api_reference/fetch.html).

thoughts?

**Comment by herumi** [comment]
I made a patch for mcl_c.js. Could you try [it](https://github.com/herumi/mcl-wasm/commit/cfcc78cfdc223a286ff2da11822df1934d583c2d)?

**Comment by firnprotocol** [comment]
i do not have experience with building mcl-wasm from source and running it locally. do you have any tips?

**Comment by herumi** [comment]
[The patch](https://github.com/herumi/mcl-wasm/commit/cfcc78cfdc223a286ff2da11822df1934d583c2d) contains pre-built mcl_c.js, so you can use it right now.

**Comment by firnprotocol** [comment]
unfortunately, my local build environment has recently broken completely, for reasons i still do not understand. even on the previous state (i.e., before applying the patch), i am getting errors in both `site` and `snap`:
```javascript
➤ YN0000: [site]: 
➤ YN0000: [site]:   Error: Unable to deserialize cloned data due to invalid or unsupported version
➤ YN0000: [site]:   .
➤ YN0000: [site]:   
➤ YN0000: [site]:   - v8.js:343 deserialize
➤ YN0000: [site]:     v8.js:343:7
➤ YN0000: [site]:   
➤ YN0000: [site]:   - serializer.js:249 deserialize
➤ YN0000: [site]:     [snap]/[@parcel]/core/lib/serializer.js:249:48
➤ YN0000: [site]:   
➤ YN0000: [site]:   - RequestTracker.js:854 loadRequestGraph
➤ YN0000: [site]:     [snap]/[@parcel]/core/lib/RequestTracker.js:854:52
➤ YN0000: [site]:   
➤ YN0000: [site]:   - RequestTracker.js:821 Function.init
➤ YN0000: [site]:     [snap]/[@parcel]/core/lib/RequestTracker.js:821:17
➤ YN0000: [site]:   
➤ YN0000: [site]:   - Parcel.js:256 Parcel._init
➤ YN0000: [site]:     [snap]/[@parcel]/core/lib/Parcel.js:256:28
➤ YN0000: [site]:   
➤ YN0000: [site]:   - Parcel.js:273 Parcel.run
➤ YN0000: [site]:     [snap]/[@parcel]/core/lib/Parcel.js:273:7
➤ YN0000: [site]:   
➤ YN0000: [site]:   - compile-gatsby-files.ts:109 compileGatsbyFiles
➤ YN0000: [site]:     [snap]/[gatsby]/src/utils/parcel/compile-gatsby-files.ts:109:29
➤ YN0000: [site]:   
➤ YN0000: [site]:   - initialize.ts:172 initialize
➤ YN0000: [site]:     [snap]/[gatsby]/src/services/initialize.ts:172:3
➤ YN0000: [site]:   
➤ YN0000: [site]: 
not finished compile gatsby files - 0.171s
➤ YN0000: [site]: 
➤ YN0000: [site]: Process exited (exit code 1), completed in 4s 381ms
➤ YN0000: [@firnprotocol/snap]: 
➤ YN0000: [@firnprotocol/snap]: <--- Last few GCs --->
➤ YN0000: [@firnprotocol/snap]: 
➤ YN0000: [@firnprotocol/snap]: [20463:0x104918000]     1227 ms: Scavenge 770.6 (803.9) -> 770.6 (803.9) MB, 31.4 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
➤ YN0000: [@firnprotocol/snap]: [20463:0x104918000]     1786 ms: Scavenge 1153.1 (1186.4) -> 1153.1 (1186.4) MB, 48.8 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
➤ YN0000: [@firnprotocol/snap]: [20463:0x104918000]     2625 ms: Scavenge 1726.9 (1760.2) -> 1726.9 (1760.2) MB, 71.8 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
➤ YN0000: [@firnprotocol/snap]: 
➤ YN0000: [@firnprotocol/snap]: 
➤ YN0000: [@firnprotocol/snap]: <--- JS stacktrace --->
➤ YN0000: [@firnprotocol/snap]: 
➤ YN0000: [@firnprotocol/snap]: FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
➤ YN0000: [@firnprotocol/snap]:  1: 0x10131a2c5 node::Abort() (.cold.1) [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]:  2: 0x1000b6169 node::Abort() [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]:  3: 0x1000b62df node::OnFatalError(char const*, char const*) [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]:  4: 0x100200bb7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]:  5: 0x100200b53 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]:  6: 0x1003aec65 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]:  7: 0x100386736 v8::internal::Factory::NewUninitializedFixedArray(int) [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]:  8: 0x100513762 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]:  9: 0x1006de7e4 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]: 10: 0x100a8ded9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/firnprotocol/emsdk/node/14.18.2_64bit/bin/node]
➤ YN0000: [@firnprotocol/snap]: 11: 0x216759fc7cdf 
➤ YN0000: [@firnprotocol/snap]: Snap evaluation error: Process exited with non-zero exit code: null
➤ YN0000: [@firnprotocol/snap]: Error: Process exited with non-zero exit code: null
➤ YN0000: [@firnprotocol/snap]:     at ChildProcess.<anonymous> (/Users/firnprotocol/snap/node_modules/@metamask/snap-utils/dist/eval.js:23:27)
➤ YN0000: [@firnprotocol/snap]:     at ChildProcess.emit (events.js:400:28)
➤ YN0000: [@firnprotocol/snap]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
➤ YN0000: [@firnprotocol/snap]: Error during initial build.
➤ YN0000: [@firnprotocol/snap]: Error: Process exited with non-zero exit code: null
➤ YN0000: [@firnprotocol/snap]:     at ChildProcess.<anonymous> (/Users/firnprotocol/snap/node_modules/@metamask/snap-utils/dist/eval.js:23:27)
➤ YN0000: [@firnprotocol/snap]:     at ChildProcess.emit (events.js:400:28)
➤ YN0000: [@firnprotocol/snap]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
➤ YN0000: [@firnprotocol/snap]: 
➤ YN0000: [@firnprotocol/snap]: Starting server...
➤ YN0000: [@firnprotocol/snap]: Server listening on: http://localhost:8080
```
i have no idea what is going on; this might take me some time to fix. apologies; i will get back to you as soon as i can.

**Comment by herumi** [comment]
I tried your snap-mcl-wasm-mwe with the modified mcl_c.js, and it seems good.

1. git clone snap-mcl-wasm-mwe.
2. yarn install
3. remove node_modules/mcl-wasm and make a symbolic link of a new mcl-wasm (dev branch) or copy it.
  - Verify mcl_c.js to comment out what you find.
5. yarn install, again
6. yarn start

**Comment by firnprotocol** [comment]
hi @herumi,

confirmed that it works!!! excellent. huge thanks.

before we proceed, can i ask, what is the plan for publishing it? will there be a special branch or version of `mcl-wasm`? or will you do this globally?

i will wonder whether this is some special emscripten flag that would fix. this. but i couldn't find it.

**Comment by herumi** [comment]
Yes, I'll merge it into the master branch and release it.

**Comment by herumi** [comment]
I've released v1.0.6 .

**Comment by firnprotocol** [comment]
thank you very much.

to be completely honest, i am slightly uncomfortable with this solution, since it _may_ have unintended effects for other users (i am not sure). i will keep looking into whether there is a "cleaner" way. for now, this works. i will keep you updated.

**Comment by firnprotocol** [comment]
hi @herumi.

i believe i have come up with a better solution: i can use `patch-package` to locally patch the package before build.

i think it would be best to revert or `unpublish` version `1.0.6`, just so that we don't have to affect other users. huge thank you for helping me diagnose this issue, and for your patience. i apologize for the trouble. let me know your thoughts.

**Comment by herumi** [comment]
Thank you for the research and feedback. I'll check https://github.com/MetaMask/snaps-monorepo/issues/1131 .

**Comment by firnprotocol** [comment]
yes, i have resolved and closed that issue.

i think you should feel free to `npm` [`unpublish`](https://docs.npmjs.com/unpublishing-packages-from-the-registry#unpublishing-a-single-version-of-a-package) `mcl-wasm@1.0.6`.

**Comment by herumi** [comment]
Okay, I don't think that it has unintended effects, so I'll remove the patch at the next release.

**Comment by firnprotocol** [comment]
sounds good!

**Comment by firnprotocol** [comment]
hi @herumi, can I follow up—was the patch removed in the recent releases? (i.e., revert cfcc78cfdc223a286ff2da11822df1934d583c2d, etc.). thanks in advance!

**Comment by herumi** [comment]
The patch caused an error.

The latest emcc does not generate the following code:
```diff
 function getBinaryPromise() {
+/*
  if (!wasmBinary && (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER)) {
   if (typeof fetch == "function" && !isFileURI(wasmBinaryFile)) {
    return fetch(wasmBinaryFile, {
@@ -374,6 +375,7 @@ function getBinaryPromise() {
    }
   }
  }
+*/
  return Promise.resolve().then(function() {
   return getBinary(wasmBinaryFile);
  });
```

Is this patch still effective?
```
--- a/src/mcl_c.js
+++ b/src/mcl_c.js
@@ -107,11 +107,11 @@ if (ENVIRONMENT_IS_NODE) {
  if (_scriptDir) {
   scriptDirectory = _scriptDir;
  }
- if (scriptDirectory.indexOf("blob:") !== 0) {
-  scriptDirectory = scriptDirectory.substr(0, scriptDirectory.replace(/[?#].*/, "")
.lastIndexOf("/") + 1);
- } else {
-  scriptDirectory = "";
- }
+// if (scriptDirectory.indexOf("blob:") !== 0) {
+//  scriptDirectory = scriptDirectory.substr(0, scriptDirectory.replace(/[?#].*/, "
").lastIndexOf("/") + 1);
+// } else {
+//  scriptDirectory = "";
+// }
  {
```

If you make a new patch, then I'll include it.

**Comment by herumi** [comment]
By the way, I thought SES was going to solve this problem not mcl.

**Comment by firnprotocol** [comment]
> By the way, I thought SES was going to solve this problem not mcl.

i think there is a misunderstanding. i do **not** need **any** patch to be included in `mcl-wasm` anymore. i am able to apply the required patch in _my own_ codebase instead. that is, I will solve the problem in the consuming code, not you or SES.

> Is this patch still effective?

i have not been able to test it recently. i can let you know soon. but I do **not** need any patch to be included upstream in `mcl-wasm` anymore. you can remove it. thank you!

**Comment by herumi** [comment]
Okay, if you have any problems, please make an issue.
