### ISSUE TITLE
Format for deserializeHexStr

### ISSUE THREAD

**Issue by noot** [herumi/mcl-wasm#3]
I am attempting to do `let s = mcl.deserializeHexStrToFr('263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3')
` but I get the error:

```
Error: err _wrapDeserialize
      at /home/elizabeth/bls-js/node_modules/mcl-wasm/mcl.js:111:28
```

The hex string appears to be of the correct length (64 chars) so I'm not sure what is going wrong.  Similarly, what is the correct format for deserializeHexStrToG1 and deserializeHexStrToG2?

**Comment by herumi** [comment]
I added some APIs. see https://github.com/herumi/mcl-wasm/commit/49afc0e8f7df26f9e0f13fe35f93ea0b320d14f8#diff-1dd241c4cd3fd1dd89c570cee98b79ddR136

**Comment by herumi** [comment]
There is no document to describe the serialization format of G1 and G2.

P = (x, y) in G1
if P.isZero() then 64-bytes zero.
otherwise,
d = x.serialize()
if (y.isOdd()) d[63] |= 0x80
see the code. https://github.com/herumi/mcl/blob/master/include/mcl/ec.hpp#L691

**Comment by herumi** [comment]
cf. https://github.com/herumi/mcl/blob/master/include/mcl/op.hpp#L77-L88

**Comment by herumi** [comment]
You can use `setStr(string, 16)` and `getStr(16)`.

```
a = new mcl.Fr()
a.setStr('ff', 16)
a.getStr()
"255"
a.getStr(16)
"ff"
```

**Comment by noot** [comment]
Thank you @herumi ! What about formatting for deserialization of Fr?

Also, when I try 
```
	let s = new mcl.Fr()
        s.setStr('263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3', 16)
        console.log(s.serializeToHexStr())
```

The output I get is `e3402046e18f271cf277b9c73a0daf8695f2c038895fd87ee41b5b2f79bd3d26` which looks like it's converting it to big endian.  Is there a way to specify big or little endian?

**Comment by herumi** [comment]
I updated mcl.js to support 0x... string (I thought that mcl.js supported the format). https://github.com/herumi/mcl-wasm/commit/84cbf5f45b059af0be972170adfdc50849a94963 .

**Comment by herumi** [comment]
>What about formatting for deserialization of Fr?

The format is a fixed-length little endian byte sequence.

Ex.
s.setStr('0x12345678')
s.serializeToHexStr()
"7856341200000000000000000000000000000000000000000000000000000000"

**Comment by taoxinyi** [comment]
`getStr(16)` will emit all the starting zero.
```js
let s = new mcl.Fr();
s.setStr('000f', 16);
console.log(s.getStr(16)); //will return f
```

**Comment by herumi** [comment]
>`getStr(16)` will emit all the starting zero.

It is the intended behavior.

**Comment by noot** [comment]
I am trying to set a Fr point to the string q as specified here: https://github.com/zkcrypto/pairing/tree/master/src/bls12_381
```
	let q = new mcl.Fr()
	q.setStr('0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab')
	return q
```
However I get the error `Error: err _wrapInput`.  How would I do this correctly? Thank you @herumi  :)

**Comment by herumi** [comment]
The value of Fr must be in [0, r-1] where r = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001.
