### ISSUE TITLE
BLS Fr setHashOf

### ISSUE THREAD

**Issue by atomictag** [herumi/mcl-wasm#33]
Hi there. I am working on a BLS12-381 scheme which requires hashing a message to the `Fr` scalar field. 

In some cases the message/pre-image is given (hence `setHashOf(preimage)` can be used) but in other cases the SHA256 hash is given - which needs to be mapped to Fr by other means. I was relying on the assumption that it was sufficient to call `setLittleEndianMod(hash)` to obtain the same result produced by `setHashOf(preimage)`. This works in some cases but not in others so I digged up the mcl code to figure out what happens under the hood.

A small test case to illustrate the situation:

```typescript
   // Helper functions
    const fromHashOf = (m: string) => {
      const fr = new mcl.Fr();
      fr.setHashOf(m);
      return fr;
    };
    const fromSha256 = (sha: Uint8Array) => {
      const fr = new mcl.Fr();
      fr.setLittleEndianMod(sha);
      return fr;
    };

    {
     // This works
      const message_0 = "message-0";
      const sha = sha256(message_0); // ce78e7c740f40722f11a530ebf14d260a9bb51effced715addf98c5a3ecfc23c
      const h1 = fromSha256(sha); // 3cc2cf3e5a8cf9dd5a71edfcef51bba960d214bf0e531af12207f440c7e778ce
      const h2 = fromHashOf(message_0); // 3cc2cf3e5a8cf9dd5a71edfcef51bba960d214bf0e531af12207f440c7e778ce
      expect(h1.isEqual(h2)).toBe(true); // OK!
    }

    {
     // This doesn't
      const message_1 = "message-1";
      const sha = sha256(message_1); // 9deb880b43bdf6f465a0afb130aed71b31cf219626f3637f577d4167cd80e5f2
      const h1 = fromSha256(sha); // 0b0a3227140682c718f0431682de1f26745c662ab1b2e867f4f6bd450b88eb9b
      const h2 = fromHashOf(message_1); // 72e580cd67417d577f63f3269621cf311bd7ae30b1afa065f4f6bd430b88eb9d
      expect(h1.isEqual(h2)).toBe(true); // KO!
    }
```

Why `fr.setLittleEndianMod(hash);` does not always behave like `fr.setHashOf(preimage)`? 

As usual, thank you so much for your time and for this great library!!

**Comment by atomictag** [comment]
Of course I am aware that the bit shift operation is a faster way to get the modulus instead of doing it naively as 
`x % 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaabn`. 
I guess I could summarize this issue as my lack of understanding of what `setLittleEndianMod` is supposed to do (since intuitively it sounds like it should do exactly the same)

**Comment by atomictag** [comment]
As far as I can tell `setLittleEndianMod` does the equivalent of `% p` (p = curve order) on the hash read as a little endian number. On the other hand, `setLittleEndian` (and indirectly `setHashOf`) seem to work like the following:

```typescript
    const setLittleEndian = (sha: Uint8Array) => {
      const L = 255n; // bit length of curve order
      const p = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001n; // curve order
      let x = os2ip(sha, "le"); // from bytes to bigint, little-endian
      // Apply masking
      x &= (1n << L) - 1n;
      if (x >= p) x &= (1n << (L - 1n)) - 1n;
      // Set the masked value (which now falls for sure within the field) directly
      const fr = new mcl.Fr();
      fr.deserializeHexStr(x.toString(16).padStart(64, "0"));
      return fr;
    };
```
So `setLittleEndian(hash_bytes)` is the correct way to replicate what `sethashOf` does (although https://github.com/herumi/mcl#how-do-i-set-the-hash-value-to-fr seems to imply `setLittleEndianMod` should be used).

I did some research on the reasons why the masking is applied (besides being clearly faster to compute than the modulo operation) - but I could not find any reference to what "standard" algorithm should be used to hash raw bytes into the scalar field (unlike `hashToCurve` which has plenty of literature). 

Thank you in advance for any clarification on this subject

**Comment by herumi** [comment]
As you write, the API is confusing for backwards compatibility. I'm sorry.

The history of the API is as follows.
1. (2016) setLittleEndian (mask and mod)
  It is masked to do the subtraction at most once.
2. setHashOf = hash + setLittleEndian
3. (2019) setLittleEndianMod (mod p)
  setHashOf did not be changed. So use Hash + setLittleEndianMod

**Comment by atomictag** [comment]
Thank you for the clarification - that's what I suspected. No worries 😀
