### ISSUE TITLE
Batch Inversion Algorithm

### ISSUE THREAD

**Issue by atomictag** [herumi/mcl-wasm#39]
It would be very useful for several use cases (e.g. DFT, KZG, Verkle trie multi-proofs, ...) to provide a native batch Inversion algorithm such as
```
invVec(vec: Fr[]): Fr[]
```
A naive javascript implementation using 2n multiplications and 1 inversion outperforms n inversions by 2x with n=1000 so I suspect a native implementation would do much better. If I am not mistaken MCL already has an optimized `invVec` function.  

Many thanks

**Comment by herumi** [comment]
I've added `invVec` for Fr and Fp at the [dev branch](https://github.com/herumi/mcl-wasm/commits/dev).
Could you try it?

**Comment by atomictag** [comment]
BTW as a minor optimization:
```
const _cloneArray = (x) => {
    const cstr = x.constructor;
    const r = new cstr();
    r.a_ = new Uint32Array(x.a_);
    return r;
};
```
could be re-written as
```
const _cloneArray = (x) => {
    const cstr = x.constructor;
    const r = new cstr();
    r.a_.set(x.a_);
    return r;
};
```
since `new cstr()` already creates the array buffer `a_`

**Comment by herumi** [comment]
I renamed `invVec` to `invVecInPlace` and append `invVec` which returns the processed value.
https://github.com/herumi/mcl-wasm/commits/dev/

Though I don't see the referenced library, my library has an overhead of copying wasm data to a JavaScript array vice versa, so invVec may be faster.

**Comment by atomictag** [comment]
Awesome! 

Updated tests:
````
Fr: vector size = 1000, runs = 1000. Average per run:
- invVecInPlace: 0.31 ms
- inVec:         0.47 ms
- inVec_js:      1.12 ms
- naive:         3.68 ms

Fp: vector size = 1000, runs = 1000. Average per run:
- invVecInPlace: 0.72 ms
- inVec:         0.89 ms
- naive:         6.70 ms

````
Looks great - thank you so much 🙏

**Comment by atomictag** [comment]
I have a question:

This is the current `_invVec` (which does not change the input vector xVec)
```typescript
const _invVec = (func, xVec) => {
    const n = xVec.length;
    if (n == 0) return [];
    const cstr = xVec[0].constructor;
    const yVec = Array.from({ length: n }, _ => new cstr());
    const stack = mcl_1.mod.stackSave();
    const yPos = mcl_1.mod.stackAlloc(xVec[0].a_.length * 4 * n); // <====== why??
    const xPos = _sarrayAllocAndCopy(xVec);
    func(yPos, xPos, n);
    // copy from WASM memory into yVec
    _saveArray(yVec, yPos);
    // restore stack and return yVec
    mcl_1.mod.stackRestore(stack);
    return yVec;
};
```
why is the `yPos` stack allocation necessary instead of doing exacrly what `invVecInPlace` and then copy into a new vector?
```typescript
const _invVec = (func, xVec) => {
    const n = xVec.length;
    if (n == 0) return [];
    // Do the same as invVecInPlace does
    const stack = mcl_1.mod.stackSave();
    const xPos = _sarrayAllocAndCopy(xVec);
    func(xPos, xPos, n);
    // Now allocate the return vector yVec
    const cstr = xVec[0].constructor;
    const yVec = Array.from({ length: n }, _ => new cstr());
    // copy from WASM memory into yVec
    _saveArray(yVec, xPos);
    // restore stack and return yVec
    mcl_1.mod.stackRestore(stack);
    return yVec;
};
```` 
Thank you for helping with my understanding!

**Comment by herumi** [comment]
Thank you for the quick comment.
You are right. I was in the process of trial and error.
https://github.com/herumi/mcl-wasm/commit/b98a45fce7ef72ca49454ad003d1a6cf4ff0b313
