### ISSUE TITLE
Is it possible to make G1=G2?

### ISSUE THREAD

**Issue by taoxinyi** [herumi/mcl-wasm#4]
I'd like to implement the following [Proxy Re-Encryption algriothm,](https://eprint.iacr.org/2005/028.pdf) is it possible to set `e : G1 x G1-> GT` ?
![pre](https://user-images.githubusercontent.com/22277258/52254053-6aeedf80-2946-11e9-8e28-57ea631405f8.png)

**Comment by herumi** [comment]
A BN and BLS12 curves are type 3 pairing, which means that G1 is not the same as G2. So you take a P in G1 and a Q in G2 and z := e(P, Q).
pk_a := aP.
Compute rk_{A to B} = e(bP, (1/a)Q) = z^(b/a) from a and pk_b and so on.

**Comment by taoxinyi** [comment]
Thank you, you are so nice.
