### ISSUE TITLE
version 1.8.0

### ISSUE THREAD

**Issue by atomictag** [herumi/mcl-wasm#42]
Hi there,
I just noticed that mcl-wasm was updated to 1.8.0 on npm but the main branch is still reflecting the last 1.7.0 version.
Also the `dev` branch seems to still be at 1.7.0.
What was published as 1.8.0?

Many thanks

**Comment by herumi** [comment]
Thank you for the notification. I forgot to push it to the master branch. I've now pushed it as v1.8.1

**Comment by atomictag** [comment]
Thank you!
