### ISSUE TITLE
Choose curve types like secp256k1 to do operations when not using pairing

### ISSUE THREAD

**Issue by taoxinyi** [herumi/mcl-wasm#5]
In original [mcl/test/ec_test.cpp](https://github.com/herumi/mcl/blob/a88d43df8e71dcab1a3a8af4e087c628f0adf922/test/ec_test.cpp), I can see doing operations like `mul` in curves like `secp224k1` and `secp256k1`. It will be extremely nice to expose these curves when not using pairing in js.

Right now, if I want to do some custom encryption functions using `add`,`mul` on an elliptic curve with no pairing involved, I can only choose from BN and BLS curves.

**Comment by herumi** [comment]
mcl-wasm has supported `secp224k1` and `secp256k1` with only `add`, `mul` operations.
https://github.com/herumi/mcl-wasm/commit/085a8c13baa197ef8471061ce2487686e960733a

**Comment by taoxinyi** [comment]
Thank you so much! I've test it and it works absolutely great!
