### ISSUE TITLE
Possible to mod order?

### ISSUE THREAD

**Issue by taoxinyi** [herumi/mcl-wasm#6]
In [ECDSA](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm), it requires x coordinate to mod order `(r = x1 mod n)`. Is it possible to achieve here? It seems `setStr`  in Fr is not working when the argument is larger than the order.

Thanks a lot!

**Comment by herumi** [comment]
The latest version supports Fr::setLittleEndianMod(Uint8Array).
Could you test it?

**Comment by taoxinyi** [comment]
Sure. By the way, how to get the order in `Uint8Array`?

**Comment by taoxinyi** [comment]
I've used it in my application and it seems great. Thank you!
